executable = a.sh
Arguments = result_$(Process).root $(remoteFILE)
# environment=PATH=$PATH;LD_LIBRARY_PATH=$LD_LIBRARY_PATH" # SUB file does not support bash variable, assign this variable at CLI

output = test_mesg_$(Process).out
error  = test_mesg_$(Process).err
log    = test_mesg_$(Process).log

+JobFlavour = 'testmatch'
should_transfer_files = YES
when_to_transfer_output = ON_EXIT_OR_EVICT
transfer_output_files = result_$(Process).root
Queue remoteFILE from testinput.txt
