executable = a.sh
Arguments = result_1.root /wk_cms3/ltsai/CRAB_FILES/UL16PostVFP_GJetPythia/GJet_Pt-40toInf_DoubleEMEnriched_MGG-80toInf_TuneCP5_13TeV_Pythia8/crab_UL16PostVFP_GJetPythia_GJet_Pt-40toInf_DoubleEMEnriched_MGG-80toInf_TuneCP5_13TeV_Pythia8/221221_083940/0000/ggtree_mc_103.root /wk_cms3/ltsai/CRAB_FILES/UL16PostVFP_GJetPythia/GJet_Pt-40toInf_DoubleEMEnriched_MGG-80toInf_TuneCP5_13TeV_Pythia8/crab_UL16PostVFP_GJetPythia_GJet_Pt-40toInf_DoubleEMEnriched_MGG-80toInf_TuneCP5_13TeV_Pythia8/221221_083940/0000/ggtree_mc_103.root
output = test5_mesg_$(Process).out
error  = test5_mesg_$(Process).err
log    = test5_mesg_$(Process).log

+JobFlavour = 'testmatch'
queue
